
FROM maven:3.8.2-eclipse-temurin-17 AS build

# Set default values for build arguments
ARG DATABASE_URL=default-database-url
ARG DATABASE_USERNAME=default-username
ARG DATABASE_PASSWORD=default-password
ARG SPRING_PROFILES_ACTIVE=default-profile
ARG DOCKERHUB_PASSWORD=default-pass

# Use the build arguments to set environment variables
ENV DATABASE_URL=$DATABASE_URL
ENV DATABASE_USERNAME=$DATABASE_USERNAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
ENV DOCKERHUB_PASSWORD=$DOCKERHUB_PASSWORD




COPY . .
# Create the /app directory and set it as the working directory
WORKDIR /backend/app

# Create a build number using the date command
RUN export BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S') && \
    echo "BUILD_NUMBER=$BUILD_NUMBER" >> build-info.properties

RUN mvn clean verify -DskipTests -Djib.to.auth.password=${DOCKERHUB_PASSWORD} -Djib.to.auth.username=tommylay1902 -Ddocker.image.tag=$BUILD_NUMBER

FROM openjdk:17.0.1-jdk-slim
COPY --from=build target/amigoscode-api-1.0-SNAPSHOT.jar amigoscode-api.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "amigoscode-api.jar"]