FROM node:19-alpine as build
## Set default values for build arguments
#ARG api_base_url

ENV api_base_url="http://localhost:8088"

#ENV API_BASE_URL = $API_BASE_URL
WORKDIR /app
COPY package*.json .
RUN npm i --silent
COPY . .
RUN echo $api_base_url
RUN echo "VITE_API_BASE_URL=${api_base_url}" > .env
EXPOSE 5173
CMD ["npm", "run", "dev"]